config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  # Named routes
  get 'pages/index', to: 'pages#index', as: 'index'
  get 'pages/about', to: 'pages#about', as: 'about'
  get 'pages/technology', to: 'pages#technology', as: 'technology'
  get 'pages/deportes', to: 'pages#deportes', as: 'deportes'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    def index
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def technology
  end

  def deportes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortalNoticias</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar bg-light">
      <div class="container-fluid">
        <%= link_to "Portal Noticias", root_path %>
        <%= link_to "About", about_path %>
        <%= link_to "Technology", technology_path %>
        <%= link_to "Deportes", deportes_path %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/deportes.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sports</title>
</head>
<body>
    <h1>Sports</h1>
</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= time_ago_in_words(Time.now + 60) %>

app/views/pages/technology.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Ruby</title>
    </head>
    <body>
        <main>
            <h1>Noticias de tecnología</h1>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat minus numquam reprehenderit doloribus pariatur sunt architecto quam nisi laboriosam neque voluptas earum beatae facere, atque cumque exercitationem facilis similique blanditiis.
            </p>
            <p>
                <%= Time.now.strftime("%d-%m-%Y") %>
            </p>
        </main>
    </body>
</html>